pub mod about_dialog;
pub mod assets_manager;
pub mod command_palette;
pub(crate) mod dialog_smoke;
mod header_actions;
pub(crate) mod icons;
pub mod launch_screen;
pub mod layout_tree;
pub mod settings_dialog;
pub(crate) mod tile_drag;
pub mod tile_view;
pub mod web_tile;
pub mod window;
pub mod workspace_view;
